const Data = [
  {
    id: "1",
    title: "Figma UI UX Design",
    category: "Breakfast",
    price: "Frontend",
    img: "cover-eng-three.jpg",
    desc: " Use Figma to get a job in UI Design, User Interface, User Experience design.",
  },
  {
    id: "2",
    title: "Learn Python",
    category: "Lunch",
    price: "Backend",
    img: "cover-eng.jpg",
    desc: " Design Web Sites and Mobile Apps that Your Users Love and Return to Again.",
  },
  {
    id: "3",
    title: "Flutter ",
    category: "Breakfast",
    price: "Design",
    img: "cover-eng-two.jpg",
    desc: "Learn how to apply User Experience (UX) principles to your website designs.",
  },
  {
    id: "4",
    title: "Figma UI UX Design",
    category: "Lunch",
    price: "Frontend",
    img: "cover-amh-two.jpg",
    desc: " Use Figma to get a job in UI Design, User Interface, User Experience design.",
  },
  {
    id: "5",
    title: "Learn Python",
    category: "Breakfast",
    price: "Backend",
    img: "cover-amh.jpg",
    desc: "Learn how to apply User Experience (UX) principles to your website designs.",
  },
  {
    id: "6",
    title: "Flutter ",
    category: "Dinner",
    price: "Design",
    img: "cover-amh-three.jpg",
    desc: "Learn how to apply User Experience (UX) principles to your website designs.",
  },
  {
    id: "7",
    title: "Flutter ",
    category: "Dinner",
    price: "Design",
    img: "oro-two.jpg",
    desc: "Learn how to apply User Experience (UX) principles to your website designs.",
  },
  {
    id: "8",
    title: "Figma UI UX Design",
    category: "Lunch",
    price: "Frontend",
    img: "oro-one.jpg",
    desc: " Use Figma to get a job in UI Design, User Interface, User Experience design.",
  },
  {
    id: "9",
    title: "Flutter ",
    category: "Breakfast",
    price: "Design",
    img: "oro-three.jpg",
    desc: "Learn how to apply User Experience (UX) principles to your website designs.",
  },
  //   {
  //     id: "10",
  //   },
];

export default Data;
